/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

import com.sun.awt.AWTUtilities;
import java.awt.Image;
import java.awt.Shape;
import java.awt.Toolkit;
import java.awt.geom.RoundRectangle2D;
import javax.swing.JFrame;

/**
 *
 * @author danlo
 */
public class FrmAgg_Usuarios extends javax.swing.JFrame {

    /**
     * Creates new form FrmAgg_Usuarios
     */
    public FrmAgg_Usuarios() {
        initComponents();
        this.setLocationRelativeTo(null); 
         Shape forma= new RoundRectangle2D.Double(0,0, this.getBounds() .width, this.getBounds() .height,40,40);
         AWTUtilities. setWindowShape(this, forma);
         setIconImage(Logo());
    }
public Image Logo(){
    Image retvalue=Toolkit.getDefaultToolkit().getImage(ClassLoader.getSystemResource("Recursos_Proyecto/B&G Morado 2.png"));
    return retvalue;
}
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelRound1 = new Controles_Personalizados.Paneles.PanelRound();
        btnMinimizar = new javax.swing.JLabel();
        btnCerrar = new javax.swing.JLabel();
        txtUsuario = new Controles_Personalizados.textfields.TextField();
        txtContraseña = new Controles_Personalizados.textfields.TextField();
        txtPIN = new Controles_Personalizados.textfields.TextField();
        CmbTipo = new Controles_Personalizados.ComboBox.combobox();
        CmbEstado = new Controles_Personalizados.ComboBox.combobox();
        btnContinuar = new Controles_Personalizados.Botones.ButtonGradient();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setPreferredSize(new java.awt.Dimension(1099, 578));
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panelRound1.setBackground(new java.awt.Color(58, 50, 75));
        panelRound1.setRoundBottomLeft(30);
        panelRound1.setRoundBottomRight(30);
        panelRound1.setRoundTopLeft(30);
        panelRound1.setRoundTopRight(30);
        panelRound1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnMinimizar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos_Proyecto/Maximizar.png"))); // NOI18N
        btnMinimizar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnMinimizar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnMinimizarMouseClicked(evt);
            }
        });
        panelRound1.add(btnMinimizar, new org.netbeans.lib.awtextra.AbsoluteConstraints(1050, 10, -1, -1));

        btnCerrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos_Proyecto/CerrarLogin.png"))); // NOI18N
        btnCerrar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnCerrar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnCerrarMousePressed(evt);
            }
        });
        panelRound1.add(btnCerrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(1070, 10, -1, -1));

        txtUsuario.setBackground(new java.awt.Color(58, 50, 75));
        txtUsuario.setForeground(new java.awt.Color(253, 255, 254));
        txtUsuario.setCaretColor(new java.awt.Color(253, 255, 254));
        txtUsuario.setDisabledTextColor(new java.awt.Color(253, 255, 254));
        txtUsuario.setFont(new java.awt.Font("Roboto Light", 0, 18)); // NOI18N
        txtUsuario.setLabelText("Nombre - usuario");
        txtUsuario.setLineColor(new java.awt.Color(253, 255, 254));
        txtUsuario.setSelectedTextColor(new java.awt.Color(58, 50, 75));
        txtUsuario.setSelectionColor(new java.awt.Color(253, 255, 254));
        panelRound1.add(txtUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 50, 310, 70));

        txtContraseña.setBackground(new java.awt.Color(58, 50, 75));
        txtContraseña.setForeground(new java.awt.Color(253, 255, 254));
        txtContraseña.setCaretColor(new java.awt.Color(253, 255, 254));
        txtContraseña.setDisabledTextColor(new java.awt.Color(253, 255, 254));
        txtContraseña.setFont(new java.awt.Font("Roboto Light", 0, 18)); // NOI18N
        txtContraseña.setLabelText("Contraseña");
        txtContraseña.setLineColor(new java.awt.Color(253, 255, 254));
        txtContraseña.setSelectedTextColor(new java.awt.Color(58, 50, 75));
        txtContraseña.setSelectionColor(new java.awt.Color(253, 255, 254));
        panelRound1.add(txtContraseña, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 130, 310, 70));

        txtPIN.setBackground(new java.awt.Color(58, 50, 75));
        txtPIN.setForeground(new java.awt.Color(253, 255, 254));
        txtPIN.setCaretColor(new java.awt.Color(253, 255, 254));
        txtPIN.setDisabledTextColor(new java.awt.Color(253, 255, 254));
        txtPIN.setFont(new java.awt.Font("Roboto Light", 0, 18)); // NOI18N
        txtPIN.setLabelText("PIN (Combinacion Propia)");
        txtPIN.setLineColor(new java.awt.Color(253, 255, 254));
        txtPIN.setSelectedTextColor(new java.awt.Color(58, 50, 75));
        txtPIN.setSelectionColor(new java.awt.Color(253, 255, 254));
        panelRound1.add(txtPIN, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 210, 310, 70));

        CmbTipo.setBackground(new java.awt.Color(58, 50, 75));
        CmbTipo.setForeground(new java.awt.Color(42, 36, 56));
        CmbTipo.setFont(new java.awt.Font("Roboto Light", 0, 18)); // NOI18N
        CmbTipo.setLabeText("Tipo - Usuario");
        CmbTipo.setLineColor(new java.awt.Color(253, 255, 254));
        panelRound1.add(CmbTipo, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 300, 310, 80));

        CmbEstado.setBackground(new java.awt.Color(58, 50, 75));
        CmbEstado.setForeground(new java.awt.Color(42, 36, 56));
        CmbEstado.setFont(new java.awt.Font("Roboto Light", 0, 18)); // NOI18N
        CmbEstado.setLabeText("Estado - Usuario");
        CmbEstado.setLineColor(new java.awt.Color(253, 255, 254));
        panelRound1.add(CmbEstado, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 400, 310, 80));

        btnContinuar.setBackground(new java.awt.Color(253, 255, 254));
        btnContinuar.setForeground(new java.awt.Color(58, 50, 75));
        btnContinuar.setText("Continuar");
        btnContinuar.setColor1(new java.awt.Color(253, 255, 254));
        btnContinuar.setColor2(new java.awt.Color(253, 255, 254));
        btnContinuar.setFont(new java.awt.Font("Roboto Black", 0, 18)); // NOI18N
        btnContinuar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnContinuarActionPerformed(evt);
            }
        });
        panelRound1.add(btnContinuar, new org.netbeans.lib.awtextra.AbsoluteConstraints(870, 500, 150, -1));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos_Proyecto/UserImg.png"))); // NOI18N
        panelRound1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 70, 490, 420));

        getContentPane().add(panelRound1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1100, 580));

        pack();
    }// </editor-fold>//GEN-END:initComponents
       
    private void btnContinuarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnContinuarActionPerformed
        // TODO add your handling code here:
        this.dispose();        
        PanelOpcionesPersonal.showinter =0;
    }//GEN-LAST:event_btnContinuarActionPerformed

    private void btnCerrarMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCerrarMousePressed
        this.dispose();
        PanelOpcionesPersonal.showinter =0;
    }//GEN-LAST:event_btnCerrarMousePressed

    private void btnMinimizarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnMinimizarMouseClicked
        // TODO add your handling code here:
        this.setExtendedState(JFrame.ICONIFIED);
    }//GEN-LAST:event_btnMinimizarMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmAgg_Usuarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmAgg_Usuarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmAgg_Usuarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmAgg_Usuarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmAgg_Usuarios().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private Controles_Personalizados.ComboBox.combobox CmbEstado;
    private Controles_Personalizados.ComboBox.combobox CmbTipo;
    private javax.swing.JLabel btnCerrar;
    private Controles_Personalizados.Botones.ButtonGradient btnContinuar;
    private javax.swing.JLabel btnMinimizar;
    private javax.swing.JLabel jLabel2;
    private Controles_Personalizados.Paneles.PanelRound panelRound1;
    private Controles_Personalizados.textfields.TextField txtContraseña;
    private Controles_Personalizados.textfields.TextField txtPIN;
    private Controles_Personalizados.textfields.TextField txtUsuario;
    // End of variables declaration//GEN-END:variables
}
