/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

import Controles_Personalizados.Calendario.DateChooser;
import com.sun.awt.AWTUtilities;
import java.awt.Image;
import java.awt.Shape;
import java.awt.Toolkit;
import java.awt.geom.RoundRectangle2D;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import Controlador.*;
/**
 *
 * @author ferna
 */
public class FrmAgg_Personal extends javax.swing.JFrame {

    /**
     * Creates new form FrmAgg_Personal
     */
    public FrmAgg_Personal() {
        initComponents();
        this.setLocationRelativeTo(null);
        Shape forma= new RoundRectangle2D.Double(0,0, this.getBounds() .width, this.getBounds() .height,40,40);
         AWTUtilities. setWindowShape(this, forma);
         dateChooser.setVisible(false);
         btnSelect.setVisible(false);
         setIconImage(Logo());
    }
    public Image Logo(){
    Image retvalue=Toolkit.getDefaultToolkit().getImage(ClassLoader.getSystemResource("Recursos_Proyecto/B&G Morado 2.png"));
    return retvalue;
}
    public int typestaff;//if type is 1, is a employee or teacher
    //and if type is 2, is a student

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelRound1 = new Controles_Personalizados.Paneles.PanelRound();
        btnCerrar = new javax.swing.JLabel();
        btnMinimizar = new javax.swing.JLabel();
        txtCorreo = new Controles_Personalizados.textfields.TextField();
        txtApellidos = new Controles_Personalizados.textfields.TextField();
        dateChooser = new Controles_Personalizados.Calendario.DateChooser();
        txtNombres = new Controles_Personalizados.textfields.TextField();
        txtDocumento = new Controles_Personalizados.textfields.TextField();
        CmbTipo1 = new Controles_Personalizados.ComboBox.combobox();
        txtNombres1 = new Controles_Personalizados.textfields.TextField();
        jLabel1 = new javax.swing.JLabel();
        btnContinuar = new Controles_Personalizados.Botones.ButtonGradient();
        txtApellidos1 = new Controles_Personalizados.textfields.TextField();
        btnCalendario = new Controles_Personalizados.Botones.ButtonGradient();
        btnSelect = new Controles_Personalizados.Botones.ButtonGradient();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(58, 50, 75));
        setUndecorated(true);
        setPreferredSize(new java.awt.Dimension(1099, 578));
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panelRound1.setBackground(new java.awt.Color(58, 50, 75));
        panelRound1.setAlignmentX(0.0F);
        panelRound1.setPreferredSize(new java.awt.Dimension(1080, 540));
        panelRound1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnCerrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos_Proyecto/CerrarLogin.png"))); // NOI18N
        btnCerrar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnCerrar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnCerrarMousePressed(evt);
            }
        });
        panelRound1.add(btnCerrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(1070, 10, -1, -1));

        btnMinimizar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos_Proyecto/Maximizar.png"))); // NOI18N
        btnMinimizar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnMinimizar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnMinimizarMouseClicked(evt);
            }
        });
        panelRound1.add(btnMinimizar, new org.netbeans.lib.awtextra.AbsoluteConstraints(1050, 10, -1, -1));

        txtCorreo.setBackground(new java.awt.Color(58, 50, 75));
        txtCorreo.setForeground(new java.awt.Color(253, 255, 254));
        txtCorreo.setCaretColor(new java.awt.Color(253, 255, 254));
        txtCorreo.setDisabledTextColor(new java.awt.Color(253, 255, 254));
        txtCorreo.setFont(new java.awt.Font("Roboto Light", 0, 18)); // NOI18N
        txtCorreo.setLabelText("Correo");
        txtCorreo.setLineColor(new java.awt.Color(253, 255, 254));
        txtCorreo.setSelectedTextColor(new java.awt.Color(58, 50, 75));
        txtCorreo.setSelectionColor(new java.awt.Color(253, 255, 254));
        panelRound1.add(txtCorreo, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 210, 310, 70));

        txtApellidos.setBackground(new java.awt.Color(58, 50, 75));
        txtApellidos.setForeground(new java.awt.Color(253, 255, 254));
        txtApellidos.setCaretColor(new java.awt.Color(253, 255, 254));
        txtApellidos.setDisabledTextColor(new java.awt.Color(253, 255, 254));
        txtApellidos.setFont(new java.awt.Font("Roboto Light", 0, 18)); // NOI18N
        txtApellidos.setLabelText("Apellidos");
        txtApellidos.setLineColor(new java.awt.Color(253, 255, 254));
        txtApellidos.setSelectedTextColor(new java.awt.Color(58, 50, 75));
        txtApellidos.setSelectionColor(new java.awt.Color(253, 255, 254));
        panelRound1.add(txtApellidos, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 130, 310, 70));

        dateChooser.setForeground(new java.awt.Color(58, 50, 75));
        panelRound1.add(dateChooser, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 280, 260, -1));

        txtNombres.setBackground(new java.awt.Color(58, 50, 75));
        txtNombres.setForeground(new java.awt.Color(253, 255, 254));
        txtNombres.setCaretColor(new java.awt.Color(253, 255, 254));
        txtNombres.setDisabledTextColor(new java.awt.Color(253, 255, 254));
        txtNombres.setFont(new java.awt.Font("Roboto Light", 0, 18)); // NOI18N
        txtNombres.setLabelText("Nombres");
        txtNombres.setLineColor(new java.awt.Color(253, 255, 254));
        txtNombres.setSelectedTextColor(new java.awt.Color(58, 50, 75));
        txtNombres.setSelectionColor(new java.awt.Color(253, 255, 254));
        panelRound1.add(txtNombres, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 50, 310, 70));

        txtDocumento.setBackground(new java.awt.Color(58, 50, 75));
        txtDocumento.setForeground(new java.awt.Color(253, 255, 254));
        txtDocumento.setCaretColor(new java.awt.Color(253, 255, 254));
        txtDocumento.setDisabledTextColor(new java.awt.Color(253, 255, 254));
        txtDocumento.setFont(new java.awt.Font("Roboto Light", 0, 18)); // NOI18N
        txtDocumento.setLabelText("Documento");
        txtDocumento.setLineColor(new java.awt.Color(253, 255, 254));
        txtDocumento.setSelectedTextColor(new java.awt.Color(58, 50, 75));
        txtDocumento.setSelectionColor(new java.awt.Color(253, 255, 254));
        panelRound1.add(txtDocumento, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 290, 310, 70));

        CmbTipo1.setBackground(new java.awt.Color(58, 50, 75));
        CmbTipo1.setForeground(new java.awt.Color(42, 36, 56));
        CmbTipo1.setFont(new java.awt.Font("Roboto Light", 0, 18)); // NOI18N
        CmbTipo1.setLabeText("Genero");
        CmbTipo1.setLineColor(new java.awt.Color(253, 255, 254));
        panelRound1.add(CmbTipo1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 370, 310, 80));

        txtNombres1.setBackground(new java.awt.Color(58, 50, 75));
        txtNombres1.setForeground(new java.awt.Color(253, 255, 254));
        txtNombres1.setCaretColor(new java.awt.Color(253, 255, 254));
        txtNombres1.setDisabledTextColor(new java.awt.Color(253, 255, 254));
        txtNombres1.setFont(new java.awt.Font("Roboto Light", 0, 18)); // NOI18N
        txtNombres1.setLabelText("Dirección");
        txtNombres1.setLineColor(new java.awt.Color(253, 255, 254));
        txtNombres1.setSelectedTextColor(new java.awt.Color(58, 50, 75));
        txtNombres1.setSelectionColor(new java.awt.Color(253, 255, 254));
        panelRound1.add(txtNombres1, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 50, 310, 70));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos_Proyecto/PersonalImgAdd.png"))); // NOI18N
        jLabel1.setPreferredSize(new java.awt.Dimension(301, 300));
        panelRound1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 130, 360, 350));

        btnContinuar.setBackground(new java.awt.Color(42, 36, 56));
        btnContinuar.setForeground(new java.awt.Color(58, 50, 75));
        btnContinuar.setText("Continuar");
        btnContinuar.setColor1(new java.awt.Color(253, 255, 254));
        btnContinuar.setColor2(new java.awt.Color(253, 255, 254));
        btnContinuar.setFont(new java.awt.Font("Roboto Black", 0, 18)); // NOI18N
        btnContinuar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnContinuarActionPerformed(evt);
            }
        });
        panelRound1.add(btnContinuar, new org.netbeans.lib.awtextra.AbsoluteConstraints(910, 520, 150, -1));

        txtApellidos1.setBackground(new java.awt.Color(58, 50, 75));
        txtApellidos1.setForeground(new java.awt.Color(253, 255, 254));
        txtApellidos1.setCaretColor(new java.awt.Color(58, 50, 75));
        txtApellidos1.setDisabledTextColor(new java.awt.Color(253, 255, 254));
        txtApellidos1.setFont(new java.awt.Font("Roboto Light", 0, 18)); // NOI18N
        txtApellidos1.setLabelText("Fecha de nacimiento");
        txtApellidos1.setLineColor(new java.awt.Color(253, 255, 254));
        txtApellidos1.setSelectedTextColor(new java.awt.Color(58, 50, 75));
        txtApellidos1.setSelectionColor(new java.awt.Color(253, 255, 254));
        panelRound1.add(txtApellidos1, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 130, 310, 70));

        btnCalendario.setBackground(new java.awt.Color(42, 36, 56));
        btnCalendario.setForeground(new java.awt.Color(58, 50, 75));
        btnCalendario.setText("Calendario");
        btnCalendario.setColor1(new java.awt.Color(253, 255, 254));
        btnCalendario.setColor2(new java.awt.Color(253, 255, 254));
        btnCalendario.setFont(new java.awt.Font("Roboto Black", 0, 18)); // NOI18N
        btnCalendario.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnCalendarioMouseClicked(evt);
            }
        });
        btnCalendario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCalendarioActionPerformed(evt);
            }
        });
        panelRound1.add(btnCalendario, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 230, 270, -1));

        btnSelect.setBackground(new java.awt.Color(42, 36, 56));
        btnSelect.setForeground(new java.awt.Color(58, 50, 75));
        btnSelect.setText("Seleccionar");
        btnSelect.setColor1(new java.awt.Color(253, 255, 254));
        btnSelect.setColor2(new java.awt.Color(253, 255, 254));
        btnSelect.setFont(new java.awt.Font("Roboto Black", 0, 18)); // NOI18N
        btnSelect.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSelectActionPerformed(evt);
            }
        });
        panelRound1.add(btnSelect, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 490, 140, 30));

        getContentPane().add(panelRound1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1100, 580));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCerrarMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCerrarMousePressed
        this.dispose();
        
    }//GEN-LAST:event_btnCerrarMousePressed

    private void btnContinuarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnContinuarActionPerformed
        // TODO add your handling code here:
        this.dispose();             
    }//GEN-LAST:event_btnContinuarActionPerformed

    private void btnCalendarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCalendarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnCalendarioActionPerformed

    private void btnCalendarioMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCalendarioMouseClicked
        if (dateChooser.isVisible()) {
            dateChooser.hide();
            btnSelect.hide();
        }else{
            dateChooser.setVisible(true);
            btnSelect.setVisible(true);
        }
    }//GEN-LAST:event_btnCalendarioMouseClicked

    private void btnSelectActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSelectActionPerformed
        dateChooser.setVisible(false);
        btnSelect.setVisible(false); 
    }//GEN-LAST:event_btnSelectActionPerformed

    private void btnMinimizarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnMinimizarMouseClicked
        // TODO add your handling code here:
        this.setExtendedState(JFrame.ICONIFIED);
    }//GEN-LAST:event_btnMinimizarMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmAgg_Personal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmAgg_Personal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmAgg_Personal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmAgg_Personal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmAgg_Personal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private Controles_Personalizados.ComboBox.combobox CmbTipo1;
    private Controles_Personalizados.Botones.ButtonGradient btnCalendario;
    private javax.swing.JLabel btnCerrar;
    private Controles_Personalizados.Botones.ButtonGradient btnContinuar;
    private javax.swing.JLabel btnMinimizar;
    private Controles_Personalizados.Botones.ButtonGradient btnSelect;
    private Controles_Personalizados.Calendario.DateChooser dateChooser;
    private javax.swing.JLabel jLabel1;
    private Controles_Personalizados.Paneles.PanelRound panelRound1;
    private Controles_Personalizados.textfields.TextField txtApellidos;
    private Controles_Personalizados.textfields.TextField txtApellidos1;
    private Controles_Personalizados.textfields.TextField txtCorreo;
    private Controles_Personalizados.textfields.TextField txtDocumento;
    private Controles_Personalizados.textfields.TextField txtNombres;
    private Controles_Personalizados.textfields.TextField txtNombres1;
    // End of variables declaration//GEN-END:variables
}
