/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

import Controles_Personalizados.Paneles.PanelRound;
import com.sun.awt.AWTUtilities;
import java.awt.Color;
import java.awt.Image;
import java.awt.MouseInfo;
import java.awt.Point;
import java.awt.Shape;
import java.awt.Toolkit;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.geom.RoundRectangle2D;
import java.awt.event.MouseListener;
import java.awt.event.MouseEvent;
import javax.swing.JFrame;


/**
 *
 * @author danlo and ferna
 */
public class FrmDashboard extends javax.swing.JFrame{
    
    /**
     * Creates new form Dashboard
     */
    public FrmDashboard(String nombre, String tipo) {
        initComponents();
        this.setLocationRelativeTo(null); 
         Shape forma= new RoundRectangle2D.Double(0,0, this.getBounds() .width, this.getBounds() .height,40,40);
         AWTUtilities. setWindowShape(this, forma);
         setIconImage(Logo());
         
         lblNombre.setText(nombre);
         lblTipo.setText(tipo); 
         
         lblNormal.setVisible(false);
         lblUsuarioDark.setVisible(false);
         lblNight.setVisible(false);
         lblSun.setVisible(false);
         PanelSeleccionUsuario.setVisible(false);
         panelSeleccionPersonal.setVisible(false);
         panelSeleccionPersonal.setVisible(false);
         panelSeleccionCarnets.setVisible(false);
         panelSeleccionVehiculos.setVisible(false);
         panelSeleccionParqueo.setVisible(false);
         panelSeleccionAccesos.setVisible(false);
         panelSeleccionContactos.setVisible(false);
         panelSeleccionAjustes.setVisible(false);
         panelSeleccionLogout.setVisible(false);
         panelOpcionesPersonal.setVisible(false);         
         
         PanelDashboard pl = new PanelDashboard();
         pl.setSize(1270,620);
         pl.setLocation(0, 0);
         
         PanelContenedorForms.removeAll();
         PanelContenedorForms.add(pl);
         PanelContenedorForms.revalidate();
         PanelContenedorForms.repaint();
        
    }
    
    public FrmDashboard() {
        initComponents();
    }
    
public Image Logo(){
    Image retvalue=Toolkit.getDefaultToolkit().getImage(ClassLoader.getSystemResource("Recursos_Proyecto/B&G Morado 2.png"));
    return retvalue;
}
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelFondo = new Controles_Personalizados.Paneles.PanelRound();
        PanelContenedor = new Controles_Personalizados.Paneles.PanelRound();
        txtBuscar = new Controles_Personalizados.BarraBusqueda.TextFieldAnimation();
        PanelFecha = new Controles_Personalizados.Paneles.PanelRound();
        lblHora = new javax.swing.JLabel();
        lblDia = new javax.swing.JLabel();
        lblSun = new javax.swing.JLabel();
        lblNight = new javax.swing.JLabel();
        lblSunset = new javax.swing.JLabel();
        PanelMO = new Controles_Personalizados.Paneles.PanelRound();
        lblNormal = new javax.swing.JLabel();
        btnMO = new javax.swing.JLabel();
        PanelDatosUs = new Controles_Personalizados.Paneles.PanelRound();
        lblNombre = new javax.swing.JLabel();
        lblTipo = new javax.swing.JLabel();
        lblUsuarioDark = new javax.swing.JLabel();
        lblUsuario = new javax.swing.JLabel();
        PanelContenedorForms = new Controles_Personalizados.Paneles.PanelRound();
        panelOpcionesPersonal = new Controles_Personalizados.Paneles.PanelRound();
        PanelSeleccionEstudiantes = new Controles_Personalizados.Paneles.PanelRound();
        btnEstudiantes = new javax.swing.JLabel();
        btnProfesores = new javax.swing.JLabel();
        panelSeleccionProfesores = new Controles_Personalizados.Paneles.PanelRound();
        btnDashboard = new javax.swing.JLabel();
        PanelSeleccionDashboard = new Controles_Personalizados.Paneles.PanelRound();
        btnUsuarios = new javax.swing.JLabel();
        btnPersonal = new javax.swing.JLabel();
        btnCarnets = new javax.swing.JLabel();
        btnVehiculos = new javax.swing.JLabel();
        PanelSeleccionUsuario = new Controles_Personalizados.Paneles.PanelRound();
        panelSeleccionPersonal = new Controles_Personalizados.Paneles.PanelRound();
        panelSeleccionCarnets = new Controles_Personalizados.Paneles.PanelRound();
        panelSeleccionVehiculos = new Controles_Personalizados.Paneles.PanelRound();
        btnParqueo = new javax.swing.JLabel();
        panelSeleccionParqueo = new Controles_Personalizados.Paneles.PanelRound();
        btnContactos = new javax.swing.JLabel();
        btnAjustes = new javax.swing.JLabel();
        panelSeleccionAjustes = new Controles_Personalizados.Paneles.PanelRound();
        panelSeleccionContactos = new Controles_Personalizados.Paneles.PanelRound();
        btnAccesos = new javax.swing.JLabel();
        panelSeleccionAccesos = new Controles_Personalizados.Paneles.PanelRound();
        btnCerrar = new javax.swing.JLabel();
        btnMinimizar = new javax.swing.JLabel();
        btnLogOut = new javax.swing.JLabel();
        panelSeleccionLogout = new Controles_Personalizados.Paneles.PanelRound();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panelFondo.setBackground(new java.awt.Color(42, 36, 56));
        panelFondo.setPreferredSize(new java.awt.Dimension(1366, 768));
        panelFondo.setRoundBottomLeft(40);
        panelFondo.setRoundBottomRight(40);
        panelFondo.setRoundTopLeft(40);
        panelFondo.setRoundTopRight(40);
        panelFondo.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        PanelContenedor.setBackground(new java.awt.Color(231, 234, 239));
        PanelContenedor.setPreferredSize(new java.awt.Dimension(1155, 729));
        PanelContenedor.setRoundBottomLeft(30);
        PanelContenedor.setRoundBottomRight(30);
        PanelContenedor.setRoundTopLeft(30);
        PanelContenedor.setRoundTopRight(30);
        PanelContenedor.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtBuscar.setBackground(new java.awt.Color(253, 255, 254));
        txtBuscar.setForeground(new java.awt.Color(42, 36, 56));
        txtBuscar.setAnimationColor(new java.awt.Color(42, 36, 56));
        txtBuscar.setHintText("Buscar");
        txtBuscar.setPreferredSize(new java.awt.Dimension(712, 52));
        txtBuscar.setSelectionColor(new java.awt.Color(42, 36, 56));
        txtBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtBuscarActionPerformed(evt);
            }
        });
        PanelContenedor.add(txtBuscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, 810, 50));

        PanelFecha.setBackground(new java.awt.Color(253, 255, 254));
        PanelFecha.setPreferredSize(new java.awt.Dimension(152, 52));
        PanelFecha.setRoundBottomLeft(20);
        PanelFecha.setRoundBottomRight(20);
        PanelFecha.setRoundTopLeft(20);
        PanelFecha.setRoundTopRight(20);
        PanelFecha.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblHora.setFont(new java.awt.Font("Roboto Black", 0, 14)); // NOI18N
        lblHora.setForeground(new java.awt.Color(42, 36, 56));
        lblHora.setText("7:00 am");
        PanelFecha.add(lblHora, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, -1, -1));

        lblDia.setFont(new java.awt.Font("Roboto Black", 0, 18)); // NOI18N
        lblDia.setForeground(new java.awt.Color(42, 36, 56));
        lblDia.setText("THU");
        PanelFecha.add(lblDia, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, -1, -1));

        lblSun.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos_Proyecto/bxs-sun.png"))); // NOI18N
        PanelFecha.add(lblSun, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, -2, -1, 60));

        lblNight.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos_Proyecto/Night.png"))); // NOI18N
        PanelFecha.add(lblNight, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, -2, -1, 60));

        lblSunset.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos_Proyecto/sunset.png"))); // NOI18N
        PanelFecha.add(lblSunset, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, -2, -1, 60));

        PanelContenedor.add(PanelFecha, new org.netbeans.lib.awtextra.AbsoluteConstraints(840, 30, 160, 60));

        PanelMO.setBackground(new java.awt.Color(253, 255, 254));
        PanelMO.setPreferredSize(new java.awt.Dimension(57, 54));
        PanelMO.setRoundBottomLeft(20);
        PanelMO.setRoundBottomRight(20);
        PanelMO.setRoundTopLeft(20);
        PanelMO.setRoundTopRight(20);
        PanelMO.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblNormal.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos_Proyecto/lblNormal.png"))); // NOI18N
        lblNormal.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblNormal.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblNormalMouseClicked(evt);
            }
        });
        PanelMO.add(lblNormal, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 40, 40));

        btnMO.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos_Proyecto/bxs-moon.png"))); // NOI18N
        btnMO.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnMO.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnMOMouseClicked(evt);
            }
        });
        PanelMO.add(btnMO, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 40, 40));

        PanelContenedor.add(PanelMO, new org.netbeans.lib.awtextra.AbsoluteConstraints(1010, 30, 70, 60));

        PanelDatosUs.setBackground(new java.awt.Color(253, 255, 254));
        PanelDatosUs.setPreferredSize(new java.awt.Dimension(174, 55));
        PanelDatosUs.setRoundBottomLeft(20);
        PanelDatosUs.setRoundBottomRight(20);
        PanelDatosUs.setRoundTopLeft(20);
        PanelDatosUs.setRoundTopRight(20);
        PanelDatosUs.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblNombre.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        lblNombre.setForeground(new java.awt.Color(42, 36, 56));
        lblNombre.setText("Usuario");
        PanelDatosUs.add(lblNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 7, -1, 30));

        lblTipo.setFont(new java.awt.Font("Roboto Black", 0, 14)); // NOI18N
        lblTipo.setForeground(new java.awt.Color(42, 36, 56));
        lblTipo.setText("Tipo usuario");
        PanelDatosUs.add(lblTipo, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 30, -1, -1));

        lblUsuarioDark.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos_Proyecto/usuario-blanco.png"))); // NOI18N
        PanelDatosUs.add(lblUsuarioDark, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 40, 60));

        lblUsuario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos_Proyecto/bxs-user-circle.png"))); // NOI18N
        PanelDatosUs.add(lblUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 40, 60));

        PanelContenedor.add(PanelDatosUs, new org.netbeans.lib.awtextra.AbsoluteConstraints(1090, 30, 170, 60));

        PanelContenedorForms.setBackground(new java.awt.Color(231, 234, 239));
        PanelContenedorForms.setRoundBottomLeft(30);
        PanelContenedorForms.setRoundBottomRight(30);
        PanelContenedorForms.setLayout(null);

        panelOpcionesPersonal.setBackground(new java.awt.Color(58, 50, 75));
        panelOpcionesPersonal.setRoundBottomLeft(20);
        panelOpcionesPersonal.setRoundBottomRight(20);
        panelOpcionesPersonal.setRoundTopLeft(20);
        panelOpcionesPersonal.setRoundTopRight(20);
        panelOpcionesPersonal.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        PanelSeleccionEstudiantes.setBackground(new java.awt.Color(42, 36, 56));
        PanelSeleccionEstudiantes.setPreferredSize(new java.awt.Dimension(122, 67));
        PanelSeleccionEstudiantes.setRoundBottomLeft(20);
        PanelSeleccionEstudiantes.setRoundBottomRight(20);
        PanelSeleccionEstudiantes.setRoundTopLeft(20);
        PanelSeleccionEstudiantes.setRoundTopRight(20);
        PanelSeleccionEstudiantes.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnEstudiantes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos_Proyecto/bxs-graduation 1.png"))); // NOI18N
        PanelSeleccionEstudiantes.add(btnEstudiantes, new org.netbeans.lib.awtextra.AbsoluteConstraints(7, 7, -1, -1));

        panelOpcionesPersonal.add(PanelSeleccionEstudiantes, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 50, 50));

        btnProfesores.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos_Proyecto/chalkboard-user-solid 1.png"))); // NOI18N
        panelOpcionesPersonal.add(btnProfesores, new org.netbeans.lib.awtextra.AbsoluteConstraints(79, 22, -1, -1));

        panelSeleccionProfesores.setBackground(new java.awt.Color(42, 36, 56));
        panelSeleccionProfesores.setPreferredSize(new java.awt.Dimension(122, 67));
        panelSeleccionProfesores.setRoundBottomLeft(20);
        panelSeleccionProfesores.setRoundBottomRight(20);
        panelSeleccionProfesores.setRoundTopLeft(20);
        panelSeleccionProfesores.setRoundTopRight(20);
        panelSeleccionProfesores.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        panelOpcionesPersonal.add(panelSeleccionProfesores, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 10, 50, 50));

        PanelContenedorForms.add(panelOpcionesPersonal);
        panelOpcionesPersonal.setBounds(10, 150, 130, 70);

        PanelContenedor.add(PanelContenedorForms, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 90, 1270, 630));

        panelFondo.add(PanelContenedor, new org.netbeans.lib.awtextra.AbsoluteConstraints(75, 29, 1270, 720));

        btnDashboard.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos_Proyecto/casita-menu.png"))); // NOI18N
        btnDashboard.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnDashboard.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnDashboardMouseClicked(evt);
            }
        });
        panelFondo.add(btnDashboard, new org.netbeans.lib.awtextra.AbsoluteConstraints(17, 117, -1, -1));

        PanelSeleccionDashboard.setBackground(new java.awt.Color(58, 50, 75));
        PanelSeleccionDashboard.setPreferredSize(new java.awt.Dimension(122, 67));
        PanelSeleccionDashboard.setRoundBottomLeft(20);
        PanelSeleccionDashboard.setRoundBottomRight(20);
        PanelSeleccionDashboard.setRoundTopLeft(20);
        PanelSeleccionDashboard.setRoundTopRight(20);
        PanelSeleccionDashboard.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        panelFondo.add(PanelSeleccionDashboard, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 110, 50, 50));

        btnUsuarios.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos_Proyecto/usuario-menu.png"))); // NOI18N
        btnUsuarios.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnUsuarios.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnUsuariosMouseClicked(evt);
            }
        });
        panelFondo.add(btnUsuarios, new org.netbeans.lib.awtextra.AbsoluteConstraints(17, 177, -1, -1));

        btnPersonal.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos_Proyecto/personal-menu.png"))); // NOI18N
        btnPersonal.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnPersonal.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnPersonalMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnPersonalMouseExited(evt);
            }
        });
        panelFondo.add(btnPersonal, new org.netbeans.lib.awtextra.AbsoluteConstraints(17, 237, -1, -1));

        btnCarnets.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos_Proyecto/carnets-menu.png"))); // NOI18N
        btnCarnets.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnCarnets.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnCarnetsMouseClicked(evt);
            }
        });
        panelFondo.add(btnCarnets, new org.netbeans.lib.awtextra.AbsoluteConstraints(17, 297, -1, -1));

        btnVehiculos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos_Proyecto/vehiculo-menu.png"))); // NOI18N
        btnVehiculos.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnVehiculos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnVehiculosMouseClicked(evt);
            }
        });
        panelFondo.add(btnVehiculos, new org.netbeans.lib.awtextra.AbsoluteConstraints(17, 354, -1, 40));

        PanelSeleccionUsuario.setBackground(new java.awt.Color(58, 50, 75));
        PanelSeleccionUsuario.setPreferredSize(new java.awt.Dimension(122, 67));
        PanelSeleccionUsuario.setRoundBottomLeft(20);
        PanelSeleccionUsuario.setRoundBottomRight(20);
        PanelSeleccionUsuario.setRoundTopLeft(20);
        PanelSeleccionUsuario.setRoundTopRight(20);
        PanelSeleccionUsuario.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        panelFondo.add(PanelSeleccionUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 170, 50, 50));

        panelSeleccionPersonal.setBackground(new java.awt.Color(58, 50, 75));
        panelSeleccionPersonal.setPreferredSize(new java.awt.Dimension(122, 67));
        panelSeleccionPersonal.setRoundBottomLeft(20);
        panelSeleccionPersonal.setRoundBottomRight(20);
        panelSeleccionPersonal.setRoundTopLeft(20);
        panelSeleccionPersonal.setRoundTopRight(20);
        panelSeleccionPersonal.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        panelFondo.add(panelSeleccionPersonal, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 230, 50, 50));

        panelSeleccionCarnets.setBackground(new java.awt.Color(58, 50, 75));
        panelSeleccionCarnets.setPreferredSize(new java.awt.Dimension(122, 67));
        panelSeleccionCarnets.setRoundBottomLeft(20);
        panelSeleccionCarnets.setRoundBottomRight(20);
        panelSeleccionCarnets.setRoundTopLeft(20);
        panelSeleccionCarnets.setRoundTopRight(20);
        panelSeleccionCarnets.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        panelFondo.add(panelSeleccionCarnets, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 290, 50, 50));

        panelSeleccionVehiculos.setBackground(new java.awt.Color(58, 50, 75));
        panelSeleccionVehiculos.setPreferredSize(new java.awt.Dimension(122, 67));
        panelSeleccionVehiculos.setRoundBottomLeft(20);
        panelSeleccionVehiculos.setRoundBottomRight(20);
        panelSeleccionVehiculos.setRoundTopLeft(20);
        panelSeleccionVehiculos.setRoundTopRight(20);
        panelSeleccionVehiculos.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        panelFondo.add(panelSeleccionVehiculos, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 350, 50, 50));

        btnParqueo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos_Proyecto/parqueo-menu.png"))); // NOI18N
        btnParqueo.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnParqueo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnParqueoMouseClicked(evt);
            }
        });
        panelFondo.add(btnParqueo, new org.netbeans.lib.awtextra.AbsoluteConstraints(17, 417, 30, -1));

        panelSeleccionParqueo.setBackground(new java.awt.Color(58, 50, 75));
        panelSeleccionParqueo.setPreferredSize(new java.awt.Dimension(122, 67));
        panelSeleccionParqueo.setRoundBottomLeft(20);
        panelSeleccionParqueo.setRoundBottomRight(20);
        panelSeleccionParqueo.setRoundTopLeft(20);
        panelSeleccionParqueo.setRoundTopRight(20);
        panelSeleccionParqueo.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        panelFondo.add(panelSeleccionParqueo, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 410, 50, 50));

        btnContactos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos_Proyecto/contactos-menu.png"))); // NOI18N
        btnContactos.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnContactos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnContactosMouseClicked(evt);
            }
        });
        panelFondo.add(btnContactos, new org.netbeans.lib.awtextra.AbsoluteConstraints(17, 535, 40, 40));

        btnAjustes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos_Proyecto/ajustes.png"))); // NOI18N
        btnAjustes.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnAjustes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnAjustesMouseClicked(evt);
            }
        });
        panelFondo.add(btnAjustes, new org.netbeans.lib.awtextra.AbsoluteConstraints(17, 625, 40, 40));

        panelSeleccionAjustes.setBackground(new java.awt.Color(58, 50, 75));
        panelSeleccionAjustes.setPreferredSize(new java.awt.Dimension(122, 67));
        panelSeleccionAjustes.setRoundBottomLeft(20);
        panelSeleccionAjustes.setRoundBottomRight(20);
        panelSeleccionAjustes.setRoundTopLeft(20);
        panelSeleccionAjustes.setRoundTopRight(20);
        panelSeleccionAjustes.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        panelFondo.add(panelSeleccionAjustes, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 620, 50, 50));

        panelSeleccionContactos.setBackground(new java.awt.Color(58, 50, 75));
        panelSeleccionContactos.setPreferredSize(new java.awt.Dimension(122, 67));
        panelSeleccionContactos.setRoundBottomLeft(20);
        panelSeleccionContactos.setRoundBottomRight(20);
        panelSeleccionContactos.setRoundTopLeft(20);
        panelSeleccionContactos.setRoundTopRight(20);
        panelSeleccionContactos.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        panelFondo.add(panelSeleccionContactos, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 530, 50, 50));

        btnAccesos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos_Proyecto/accesos-menu.png"))); // NOI18N
        btnAccesos.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnAccesos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnAccesosMouseClicked(evt);
            }
        });
        panelFondo.add(btnAccesos, new org.netbeans.lib.awtextra.AbsoluteConstraints(17, 476, 40, 40));

        panelSeleccionAccesos.setBackground(new java.awt.Color(58, 50, 75));
        panelSeleccionAccesos.setPreferredSize(new java.awt.Dimension(122, 67));
        panelSeleccionAccesos.setRoundBottomLeft(20);
        panelSeleccionAccesos.setRoundBottomRight(20);
        panelSeleccionAccesos.setRoundTopLeft(20);
        panelSeleccionAccesos.setRoundTopRight(20);
        panelSeleccionAccesos.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        panelFondo.add(panelSeleccionAccesos, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 470, 50, 50));

        btnCerrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos_Proyecto/CerrarLogin.png"))); // NOI18N
        btnCerrar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnCerrar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnCerrarMousePressed(evt);
            }
        });
        panelFondo.add(btnCerrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(1330, 10, -1, -1));

        btnMinimizar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos_Proyecto/Maximizar.png"))); // NOI18N
        btnMinimizar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnMinimizar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnMinimizarMouseClicked(evt);
            }
        });
        panelFondo.add(btnMinimizar, new org.netbeans.lib.awtextra.AbsoluteConstraints(1310, 10, -1, -1));

        btnLogOut.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos_Proyecto/log-out.png"))); // NOI18N
        btnLogOut.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnLogOut.setPreferredSize(new java.awt.Dimension(35, 35));
        btnLogOut.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnLogOutMouseClicked(evt);
            }
        });
        panelFondo.add(btnLogOut, new org.netbeans.lib.awtextra.AbsoluteConstraints(23, 687, -1, -1));

        panelSeleccionLogout.setBackground(new java.awt.Color(58, 50, 75));
        panelSeleccionLogout.setPreferredSize(new java.awt.Dimension(122, 67));
        panelSeleccionLogout.setRoundBottomLeft(20);
        panelSeleccionLogout.setRoundBottomRight(20);
        panelSeleccionLogout.setRoundTopLeft(20);
        panelSeleccionLogout.setRoundTopRight(20);
        panelSeleccionLogout.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        panelFondo.add(panelSeleccionLogout, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 680, 50, 50));

        getContentPane().add(panelFondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    PanelOpcionesPersonal _oppersonal = new PanelOpcionesPersonal();
    Point point = MouseInfo.getPointerInfo().getLocation();
    
    FrmPersonalSinCarnet addCarnet = new FrmPersonalSinCarnet();
    FrmAgg_Usuarios addUsuarios = new FrmAgg_Usuarios();
    FrmAgg_Personal addPersonal = new FrmAgg_Personal();
    FrmPersonal_AggVehiculo addVehiculo = new FrmPersonal_AggVehiculo();
    
    
    //Interface mode
    void DarkMode(){
        
         lblNormal.setVisible(true);
         lblUsuarioDark.setVisible(true);
         panelFondo.setBackground(new Color(32,34,37));
         PanelContenedor.setBackground(new Color(47,49,54));
         PanelMO.setBackground(new Color(32,34,37));
         PanelFecha.setBackground(new Color(32,34,37));
         PanelDatosUs.setBackground(new Color(32,34,37));
         lblDia.setForeground(Color.WHITE);
         lblHora.setForeground(Color.WHITE);
         lblNombre.setForeground(Color.WHITE);
         lblTipo.setForeground(Color.WHITE);
        txtBuscar.setBackground(new Color(32,34,37));
        txtBuscar.setForeground(Color.WHITE);
        txtBuscar.setAnimationColor(new Color(32,34,37));
        txtBuscar.setCaretColor(Color.WHITE);
        PanelContenedorForms.setBackground(new Color(47,49,54));
    }    
    void NormalMode(){
        
         lblNormal.setVisible(false);
         lblUsuarioDark.setVisible(false);
         panelFondo.setBackground(new Color(42,36,56));
         PanelContenedor.setBackground(new Color(231,234,239));
         PanelMO.setBackground(new Color(253,255,254));
         PanelFecha.setBackground(new Color(253,255,254));
         PanelDatosUs.setBackground(new Color(253,255,254));
         lblDia.setForeground(new Color(42,36,56));
         lblHora.setForeground(new Color(42,36,56));
         lblNombre.setForeground(new Color(42,36,56));
         lblTipo.setForeground(new Color(42,36,56));
        txtBuscar.setBackground(new Color(253,255,254));
        txtBuscar.setForeground(new Color(42,36,56));
        //PanelGrafica1.setBackground(new Color(253,255,254));
        //PanelGrafica2.setBackground(new Color(253,255,254));
        //PanelGrafica3.setBackground(new Color(253,255,254));
        //PanelNotificaciones.setForeground(new Color(42,36,56));
        //PanelNotificaciones.setBackground(new Color(253,255,254));
        txtBuscar.setAnimationColor(new Color(42,36,56));
        txtBuscar.setCaretColor(new Color(42,36,56));
        
    }
    //show Panel Action
    //Cierra los demás panels
    //agrega sobre el panel contenedor el que se quiere modificar
    //y cierra los formularios hijos abiertos <-- EN PRUEBAS
    public void showPanelDash(){
        PanelSeleccionDashboard.setVisible(true);
        PanelSeleccionUsuario.setVisible(false);
        panelSeleccionPersonal.setVisible(false);
        panelSeleccionCarnets.setVisible(false);
        panelSeleccionVehiculos.setVisible(false);
        panelSeleccionParqueo.setVisible(false);
        panelSeleccionAccesos.setVisible(false);
        panelSeleccionLogout.setVisible(false);
        panelSeleccionContactos.setVisible(false);
        panelSeleccionAjustes.setVisible(false);
        
        PanelDashboard pl = new PanelDashboard();
         pl.setSize(1270,620);
         pl.setLocation(0, 0);
         
         PanelContenedorForms.removeAll();
         PanelContenedorForms.add(pl);
         PanelContenedorForms.revalidate();
         PanelContenedorForms.repaint();
    }    
    public void showPanelUsers(){
        PanelSeleccionDashboard.setVisible(false);
        PanelSeleccionUsuario.setVisible(true);
        panelSeleccionPersonal.setVisible(false);
        panelSeleccionCarnets.setVisible(false);
        panelSeleccionLogout.setVisible(false);
        panelSeleccionVehiculos.setVisible(false);
        panelSeleccionParqueo.setVisible(false);
        panelSeleccionAccesos.setVisible(false);
        panelSeleccionContactos.setVisible(false);
        panelSeleccionAjustes.setVisible(false);
        
        PanelUsuarios pl = new PanelUsuarios();
         pl.setSize(1270,620);
         pl.setLocation(0, 0);
         
         PanelContenedorForms.removeAll();
         PanelContenedorForms.add(pl);
         PanelContenedorForms.revalidate();
         PanelContenedorForms.repaint();
    }
    public void showPanelStudents(){
        PanelSeleccionDashboard.setVisible(false);
        PanelSeleccionUsuario.setVisible(false);
        panelSeleccionPersonal.setVisible(true);
        panelSeleccionLogout.setVisible(false);
        panelSeleccionCarnets.setVisible(false);
        panelSeleccionVehiculos.setVisible(false);
        panelSeleccionParqueo.setVisible(false);
        panelSeleccionAccesos.setVisible(false);
        panelSeleccionContactos.setVisible(false);
        panelSeleccionAjustes.setVisible(false);
        
        PanelEstudiantes pl = new PanelEstudiantes();
         pl.setSize(1270,620);
         pl.setLocation(0, 0);
         
         PanelContenedorForms.removeAll();
         PanelContenedorForms.add(pl);
         PanelContenedorForms.revalidate();
         PanelContenedorForms.repaint();
    }
    public void showPanelTeachers(){
        PanelSeleccionDashboard.setVisible(false);
        PanelSeleccionUsuario.setVisible(false);
        panelSeleccionPersonal.setVisible(false);
        panelSeleccionLogout.setVisible(false);
        panelSeleccionCarnets.setVisible(false);
        panelSeleccionVehiculos.setVisible(false);
        panelSeleccionParqueo.setVisible(false);
        panelSeleccionAccesos.setVisible(false);
        panelSeleccionContactos.setVisible(false);
        panelSeleccionAjustes.setVisible(false);
        
        PanelProfesores pl = new PanelProfesores();
         pl.setSize(1270,620);
         pl.setLocation(0, 0);
         
         PanelContenedorForms.removeAll();
         PanelContenedorForms.add(pl);
         PanelContenedorForms.revalidate();
         PanelContenedorForms.repaint();
    }
    public void showPanelCarn(){
        PanelSeleccionUsuario.setVisible(false);
        panelSeleccionPersonal.setVisible(false);
        panelSeleccionCarnets.setVisible(true);
        panelSeleccionVehiculos.setVisible(false);
        panelSeleccionParqueo.setVisible(false);
        panelSeleccionAccesos.setVisible(false);
        panelSeleccionContactos.setVisible(false);
        panelSeleccionAjustes.setVisible(false);
        panelSeleccionLogout.setVisible(false);        
        
        PanelCarnets pl = new PanelCarnets();
         pl.setSize(1270,620);
         pl.setLocation(0, 0);
         
         PanelContenedorForms.removeAll();
         PanelContenedorForms.add(pl);
         PanelContenedorForms.revalidate();
         PanelContenedorForms.repaint();
    }
    public void showPanelCars(){
        PanelSeleccionDashboard.setVisible(false);
        PanelSeleccionUsuario.setVisible(false);
        panelSeleccionPersonal.setVisible(false);
        panelSeleccionCarnets.setVisible(false);
        panelSeleccionVehiculos.setVisible(true);
        panelSeleccionParqueo.setVisible(false);
        panelSeleccionAccesos.setVisible(false);
        panelSeleccionContactos.setVisible(false);
        panelSeleccionAjustes.setVisible(false);
        panelSeleccionLogout.setVisible(false);
        
        PanelVehiculos pl = new PanelVehiculos();
         pl.setSize(1270,620);
         pl.setLocation(0, 0);
         
         PanelContenedorForms.removeAll();
         PanelContenedorForms.add(pl);
         PanelContenedorForms.revalidate();
         PanelContenedorForms.repaint();
    }
    public void showPanelPark(){
        PanelSeleccionDashboard.setVisible(false);
        PanelSeleccionUsuario.setVisible(false);
        panelSeleccionPersonal.setVisible(false);
        panelSeleccionCarnets.setVisible(false);
        panelSeleccionVehiculos.setVisible(false);
        panelSeleccionParqueo.setVisible(true);
        panelSeleccionAccesos.setVisible(false);
        panelSeleccionContactos.setVisible(false);
        panelSeleccionAjustes.setVisible(false);
        panelSeleccionLogout.setVisible(false);
        
         PanelParqueo pl = new PanelParqueo();
         pl.setSize(1270,620);
         pl.setLocation(0, 0);
         
         PanelContenedorForms.removeAll();
         PanelContenedorForms.add(pl);
         PanelContenedorForms.revalidate();
         PanelContenedorForms.repaint(); 
    }
    public void showPanelConts(){
        PanelSeleccionDashboard.setVisible(false);
        PanelSeleccionUsuario.setVisible(false);
        panelSeleccionPersonal.setVisible(false);
        panelSeleccionCarnets.setVisible(false);
        panelSeleccionVehiculos.setVisible(false);
        panelSeleccionParqueo.setVisible(false);
        panelSeleccionAccesos.setVisible(false);
        panelSeleccionContactos.setVisible(true);
        panelSeleccionAjustes.setVisible(false);
        panelSeleccionLogout.setVisible(false);
        
        PanelContactos pl = new PanelContactos();
         pl.setSize(1270,620);
         pl.setLocation(0, 0);
         
         PanelContenedorForms.removeAll();
         PanelContenedorForms.add(pl);
         PanelContenedorForms.revalidate();
         PanelContenedorForms.repaint();
    }
    public void showPanelSett(){
        PanelSeleccionDashboard.setVisible(false);
        PanelSeleccionUsuario.setVisible(false);
        panelSeleccionPersonal.setVisible(false);
        panelSeleccionCarnets.setVisible(false);
        panelSeleccionVehiculos.setVisible(false);
        panelSeleccionParqueo.setVisible(false);
        panelSeleccionAccesos.setVisible(false);
        panelSeleccionContactos.setVisible(false);
        panelSeleccionLogout.setVisible(false);
        panelSeleccionAjustes.setVisible(true);
        
        PanelAjustes pl = new PanelAjustes();
         pl.setSize(1270,620);
         pl.setLocation(0, 0);
         
         PanelContenedorForms.removeAll();
         PanelContenedorForms.add(pl);
         PanelContenedorForms.revalidate();
         PanelContenedorForms.repaint();
    }
    public void showPanelAcces(){
        PanelSeleccionDashboard.setVisible(false);
        PanelSeleccionUsuario.setVisible(false);
        panelSeleccionPersonal.setVisible(false);
        panelSeleccionCarnets.setVisible(false);
        panelSeleccionVehiculos.setVisible(false);
        panelSeleccionParqueo.setVisible(false);
        panelSeleccionAccesos.setVisible(true);
        panelSeleccionContactos.setVisible(false);
        panelSeleccionLogout.setVisible(false);
        panelSeleccionAjustes.setVisible(false);
        
        PanelAccesos pl = new PanelAccesos();
         pl.setSize(1270,620);
         pl.setLocation(0, 0);
         
         PanelContenedorForms.removeAll();
         PanelContenedorForms.add(pl);
         PanelContenedorForms.revalidate();
         PanelContenedorForms.repaint();
    }   
    public void showPanelOptionPers(){//obtiene donde esta el boton y muestra el JFrame en la posición cercana del button

        if (_oppersonal.isShowing()) {
            _oppersonal.setVisible(true);
        }else{
            _oppersonal.setVisible(true);
                //MODIFICAR LAS MEDIDAS DONDE SALGA A LA PAR DEL BOTON
                //DISCUTIR, POR SI ALGUIEN TIENE MEJOR IDEA
            int x =btnPersonal.getX();
            int y = btnPersonal.getY();
            _oppersonal.setLocation(x+354, y+110);
        }        
        /*panelOpcionesPersonal.setVisible(true);*/
        //this.showp
    }
    
    void Logout(){
        PanelSeleccionDashboard.setVisible(false);
        PanelSeleccionUsuario.setVisible(false);
        panelSeleccionPersonal.setVisible(false);
        panelSeleccionCarnets.setVisible(false);
        panelSeleccionVehiculos.setVisible(false);
        panelSeleccionParqueo.setVisible(false);
        panelSeleccionAccesos.setVisible(false);
        panelSeleccionContactos.setVisible(false);
        panelSeleccionLogout.setVisible(true);
        panelSeleccionAjustes.setVisible(false);
        
        this.dispose();
        FrmLogin login = new FrmLogin();
        login.setVisible(true);
    }
    
    private void txtBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtBuscarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtBuscarActionPerformed

    PanelDashboard _pnldash = new PanelDashboard();
    PanelUsuarios _pnlusers = new PanelUsuarios();
    
    private void lblNormalMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblNormalMouseClicked
        // TODO add your handling code here:
        NormalMode();
        ValidacionesSistema.ValidacionesBeep_Go.Modo = 2;
        if (_pnldash.isShowing()) {
            
            _pnldash.hide();
            showPanelDash();
        }
    }//GEN-LAST:event_lblNormalMouseClicked

    private void btnMOMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnMOMouseClicked
        // TODO add your handling code here:
        DarkMode();
        ValidacionesSistema.ValidacionesBeep_Go.Modo= 1;        
        _pnldash.hide();
        if (_pnldash.isVisible()) {
            
            showPanelDash();
        }
    }//GEN-LAST:event_btnMOMouseClicked

    private void btnDashboardMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnDashboardMouseClicked
        this.showPanelDash();
    }//GEN-LAST:event_btnDashboardMouseClicked

    private void btnUsuariosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnUsuariosMouseClicked
        this.showPanelUsers();
    }//GEN-LAST:event_btnUsuariosMouseClicked

    private void btnPersonalMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnPersonalMouseClicked
        showPanelOptionPers(); 
    }//GEN-LAST:event_btnPersonalMouseClicked

    private void btnCarnetsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCarnetsMouseClicked
        this.showPanelCarn();
    }//GEN-LAST:event_btnCarnetsMouseClicked

    private void btnVehiculosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnVehiculosMouseClicked
        this.showPanelCars();
    }//GEN-LAST:event_btnVehiculosMouseClicked

    private void btnParqueoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnParqueoMouseClicked
        this.showPanelPark();
    }//GEN-LAST:event_btnParqueoMouseClicked

    private void btnContactosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnContactosMouseClicked
      this.showPanelConts();
    }//GEN-LAST:event_btnContactosMouseClicked

    private void btnAjustesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAjustesMouseClicked
        this.showPanelSett();
    }//GEN-LAST:event_btnAjustesMouseClicked

    private void btnAccesosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAccesosMouseClicked
        this.showPanelAcces();
    }//GEN-LAST:event_btnAccesosMouseClicked

    private void btnCerrarMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCerrarMousePressed
        System.exit(0);
    }//GEN-LAST:event_btnCerrarMousePressed

    private void btnPersonalMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnPersonalMouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_btnPersonalMouseExited

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
        switch (PanelOpcionesPersonal.getShowinter()) {
            case 0:
                
                break;
            case 1:
                showPanelStudents();
              
                break;
            case 2:
                showPanelTeachers();
                
            break;
            default:
                break;
        }     
        switch(ValidacionesSistema.ValidacionesBeep_Go.getModo()){
            case 1:
                break;
        }
    }//GEN-LAST:event_formWindowActivated

    private void btnLogOutMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnLogOutMouseClicked
        Logout();
    }//GEN-LAST:event_btnLogOutMouseClicked

    private void btnMinimizarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnMinimizarMouseClicked
        // TODO add your handling code here:
        this.setExtendedState(JFrame.ICONIFIED);
    }//GEN-LAST:event_btnMinimizarMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmDashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmDashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmDashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmDashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmDashboard().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private Controles_Personalizados.Paneles.PanelRound PanelContenedor;
    public Controles_Personalizados.Paneles.PanelRound PanelContenedorForms;
    private Controles_Personalizados.Paneles.PanelRound PanelDatosUs;
    private Controles_Personalizados.Paneles.PanelRound PanelFecha;
    private Controles_Personalizados.Paneles.PanelRound PanelMO;
    private Controles_Personalizados.Paneles.PanelRound PanelSeleccionDashboard;
    private Controles_Personalizados.Paneles.PanelRound PanelSeleccionEstudiantes;
    private Controles_Personalizados.Paneles.PanelRound PanelSeleccionUsuario;
    private javax.swing.JLabel btnAccesos;
    private javax.swing.JLabel btnAjustes;
    private javax.swing.JLabel btnCarnets;
    private javax.swing.JLabel btnCerrar;
    private javax.swing.JLabel btnContactos;
    private javax.swing.JLabel btnDashboard;
    private javax.swing.JLabel btnEstudiantes;
    private javax.swing.JLabel btnLogOut;
    private javax.swing.JLabel btnMO;
    private javax.swing.JLabel btnMinimizar;
    private javax.swing.JLabel btnParqueo;
    private javax.swing.JLabel btnPersonal;
    private javax.swing.JLabel btnProfesores;
    private javax.swing.JLabel btnUsuarios;
    private javax.swing.JLabel btnVehiculos;
    private javax.swing.JLabel lblDia;
    private javax.swing.JLabel lblHora;
    private javax.swing.JLabel lblNight;
    private javax.swing.JLabel lblNombre;
    private javax.swing.JLabel lblNormal;
    private javax.swing.JLabel lblSun;
    private javax.swing.JLabel lblSunset;
    private javax.swing.JLabel lblTipo;
    private javax.swing.JLabel lblUsuario;
    private javax.swing.JLabel lblUsuarioDark;
    private Controles_Personalizados.Paneles.PanelRound panelFondo;
    private Controles_Personalizados.Paneles.PanelRound panelOpcionesPersonal;
    private Controles_Personalizados.Paneles.PanelRound panelSeleccionAccesos;
    private Controles_Personalizados.Paneles.PanelRound panelSeleccionAjustes;
    private Controles_Personalizados.Paneles.PanelRound panelSeleccionCarnets;
    private Controles_Personalizados.Paneles.PanelRound panelSeleccionContactos;
    private Controles_Personalizados.Paneles.PanelRound panelSeleccionLogout;
    private Controles_Personalizados.Paneles.PanelRound panelSeleccionParqueo;
    private Controles_Personalizados.Paneles.PanelRound panelSeleccionPersonal;
    private Controles_Personalizados.Paneles.PanelRound panelSeleccionProfesores;
    private Controles_Personalizados.Paneles.PanelRound panelSeleccionVehiculos;
    private Controles_Personalizados.BarraBusqueda.TextFieldAnimation txtBuscar;
    // End of variables declaration//GEN-END:variables

}
