/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

import java.awt.Color;

/**
 *
 * @author danlo
 */
public class PanelDashboard extends javax.swing.JPanel {

    /**
     * Creates new form PanelDashboard
     */
    public PanelDashboard() {
        initComponents();
        mod();
    }
    public void mode(){
        switch(ValidacionesSistema.ValidacionesBeep_Go.getModo()){
            case 1: 
                PanelFondo.setBackground(new Color(47,49,54));
                PanelGrafica1.setBackground(new Color(32,34,37));
                PanelGrafica2.setBackground(new Color(32,34,37));
                PanelGrafica3.setBackground(new Color(32,34,37));
                lblNoti.setForeground(Color.WHITE);
                PanelNotificaciones.setBackground(new Color(32,34,37)); 
                break;
            case 2:
                PanelFondo.setBackground(new Color(231,234,239));
                PanelGrafica1.setBackground(new Color(253,255,254));
                PanelGrafica2.setBackground(new Color(253,255,254));
                PanelGrafica3.setBackground(new Color(253,255,254));
                lblNoti.setForeground(Color.BLACK);
                PanelNotificaciones.setBackground(new Color(253,255,254));
                break;
                
        }
    }

    public void mod(){
        if (ValidacionesSistema.ValidacionesBeep_Go.getModo() == 1) {
            PanelFondo.setBackground(new Color(47,49,54));
            PanelGrafica1.setBackground(new Color(32,34,37));
            PanelGrafica2.setBackground(new Color(32,34,37));
            PanelGrafica3.setBackground(new Color(32,34,37));
            lblNoti.setForeground(Color.WHITE);
            PanelNotificaciones.setBackground(new Color(32,34,37)); 
        }else if(ValidacionesSistema.ValidacionesBeep_Go.getModo() == 2){
            PanelFondo.setBackground(new Color(231,234,239));
            PanelGrafica1.setBackground(new Color(253,255,254));
            PanelGrafica2.setBackground(new Color(253,255,254));
            PanelGrafica3.setBackground(new Color(253,255,254));
            lblNoti.setForeground(Color.BLACK);
            PanelNotificaciones.setBackground(new Color(253,255,254));             
        }
    }
     /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PanelFondo = new Controles_Personalizados.Paneles.PanelRound();
        PanelGrafica1 = new Controles_Personalizados.Paneles.PanelRound();
        PanelGrafica2 = new Controles_Personalizados.Paneles.PanelRound();
        PanelNotificaciones = new Controles_Personalizados.Paneles.PanelRound();
        lblNoti = new javax.swing.JLabel();
        PanelGrafica3 = new Controles_Personalizados.Paneles.PanelRound();

        setBackground(new java.awt.Color(231, 234, 239));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        PanelFondo.setBackground(new java.awt.Color(231, 234, 239));
        PanelFondo.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        PanelGrafica1.setBackground(new java.awt.Color(253, 255, 254));
        PanelGrafica1.setPreferredSize(new java.awt.Dimension(562, 293));
        PanelGrafica1.setRoundBottomLeft(20);
        PanelGrafica1.setRoundBottomRight(20);
        PanelGrafica1.setRoundTopLeft(20);
        PanelGrafica1.setRoundTopRight(20);
        PanelGrafica1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        PanelFondo.add(PanelGrafica1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 680, 300));

        PanelGrafica2.setBackground(new java.awt.Color(253, 255, 254));
        PanelGrafica2.setPreferredSize(new java.awt.Dimension(361, 292));
        PanelGrafica2.setRoundBottomLeft(20);
        PanelGrafica2.setRoundBottomRight(20);
        PanelGrafica2.setRoundTopLeft(20);
        PanelGrafica2.setRoundTopRight(20);
        PanelGrafica2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        PanelFondo.add(PanelGrafica2, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 10, -1, 300));

        PanelNotificaciones.setBackground(new java.awt.Color(253, 255, 254));
        PanelNotificaciones.setPreferredSize(new java.awt.Dimension(165, 602));
        PanelNotificaciones.setRoundBottomLeft(20);
        PanelNotificaciones.setRoundBottomRight(20);
        PanelNotificaciones.setRoundTopLeft(20);
        PanelNotificaciones.setRoundTopRight(20);
        PanelNotificaciones.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblNoti.setFont(new java.awt.Font("Roboto Black", 0, 14)); // NOI18N
        lblNoti.setForeground(new java.awt.Color(42, 36, 56));
        lblNoti.setText("Notificaciones");
        PanelNotificaciones.add(lblNoti, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));

        PanelFondo.add(PanelNotificaciones, new org.netbeans.lib.awtextra.AbsoluteConstraints(1080, 13, 180, 600));

        PanelGrafica3.setBackground(new java.awt.Color(253, 255, 254));
        PanelGrafica3.setPreferredSize(new java.awt.Dimension(938, 293));
        PanelGrafica3.setRoundBottomLeft(20);
        PanelGrafica3.setRoundBottomRight(20);
        PanelGrafica3.setRoundTopLeft(20);
        PanelGrafica3.setRoundTopRight(20);
        PanelGrafica3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        PanelFondo.add(PanelGrafica3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 320, 1050, -1));

        add(PanelFondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1270, 620));
    }// </editor-fold>//GEN-END:initComponents

    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private Controles_Personalizados.Paneles.PanelRound PanelFondo;
    private Controles_Personalizados.Paneles.PanelRound PanelGrafica1;
    private Controles_Personalizados.Paneles.PanelRound PanelGrafica2;
    private Controles_Personalizados.Paneles.PanelRound PanelGrafica3;
    private Controles_Personalizados.Paneles.PanelRound PanelNotificaciones;
    private javax.swing.JLabel lblNoti;
    // End of variables declaration//GEN-END:variables
}
